name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi cek
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      - name: Debug APK build
        run: gradle :app:assembleDebug --stacktrace --info

      - name: APK dosyalarini bul
        if: always()
        run: find . -type f | grep "\.apk" || true

      - name: APK yukle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/*.apk
